%% Plots for simulation results FOC 

%% Torque, speed and current
% figure(1)
% subplot(3,1,1)
% plot(torques,'Linewidth',1);
% %xlim([0.8 0.8+3*Tn])
% ylim([-20 40])
% legend('T_e', 'T_L','fontsize',14)
% xlabel('Time [s]','fontsize',14)
% ylabel('Torques [Nm]','fontsize',14)
% title(' ')
% set(gca,'FontSize',14)
% subplot(3,1,2)
% plot(speed_ref,'Linewidth',1);
% %xlim([0.8 0.8+3*Tn])
% ylim([0 500])
% legend('w_{ref}','w_r','fontsize',14)
% xlabel('Time [s]','fontsize',14)
% ylabel('Rotor speed [rpm]','fontsize',14)
% title(' ')
% subplot(3,1,3)
% plot(currents,'Linewidth',1);
% %xlim([0.8 0.8+3*Tn])
% ylim([-300 400])
% legend('I_a', 'I_b', 'I_c','fontsize',14)
% xlabel('Time [s]','fontsize',14)
% ylabel('Currents [A]','fontsize',14)
% set(gca,'FontSize',14)
% title(' ')
% 
% %% Id and Iq current
% 
% figure(2)
% plot(id,'Linewidth',1)
% legend('I_d,ref', 'I_d','fontsize',14)
% xlabel('Time [s]','fontsize',14)
% ylabel('Direct current [A]','fontsize',14)
% ylim([0 181])
% set(gca,'FontSize',14)
% title(' ')
% 
% figure(3)
% plot(iq,'Linewidth',1)
% legend('I_q,ref','I_q','fontsize',14)
% xlabel('Time [s]','fontsize',14)
% ylabel('Quadrature current [A]','fontsize',14)
% ylim([-210 210])
% set(gca,'FontSize',14)
% title(' ')
% 
% %% Torques 
% 
% figure(4)
% plot(Tref,'Linewidth',1)
% legend('T_e,ref','T_e')
% xlabel('Time [s]','fontsize',14)
% ylabel('Electromagnetic torque [Nm]','fontsize',12)
% ylim([-20 20])
% set(gca,'FontSize',14)
% title(' ')

figure(5)
subplot(2,1,1)
plot(id,'Linewidth',1)
xlim([0 10])
ylim([0 180])
legend('Id_{ref}','I_d','fontsize',14)
xlabel('Time [s]','fontsize',14)
ylabel('Direct current [A]','fontsize',14)
title(' ')
set(gca,'FontSize',14)
subplot(2,1,2)
plot(iq,'Linewidth',1);
xlim([0 10])
ylim([0 150])
legend('Iq_{ref}', 'I_q','fontsize',14)
xlabel('Time [s]','fontsize',14)
ylabel('Quadrature current [A]','fontsize',14)
title(' ')
set(gca,'FontSize',14)

figure(6)
subplot(2,1,1)
plot(Tref,'Linewidth',1)
legend('Te_{ref}','T_e','fontsize',14)
xlabel('Time [s]','fontsize',14)
ylabel('Electromagnetic torque [Nm]','fontsize',14)
xlim([0 10])
ylim([0 15])
set(gca,'FontSize',14)
title(' ')
subplot(2,1,2)
plot(speed,'Linewidth',1);
xlim([0 10])
ylim([0 2000])
legend('w_{r}','w_r','fontsize',14)
xlabel('Time [s]','fontsize',14)
ylabel('Rotor speed [rpm]','fontsize',14)
title(' ')
set(gca,'FontSize',14)

figure(7)
plot(currents,'Linewidth',1);
xlim([0 5])
ylim([-300 300])
legend('I_a', 'I_b', 'I_c','fontsize',14)
xlabel('Time [s]','fontsize',14)
ylabel('Currents [A]','fontsize',14)
set(gca,'FontSize',14)
title(' ')
